version: '3'
services:
  backend:
    build:
      context: ./AI_search_engine_app
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./AI_search_engine_app:/app
    environment:
      FLASK_ENV: development

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend
